# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name=uuid.uuid4)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=64)),
                ('phone_number', models.BigIntegerField(db_index=True)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Regular')], default=2)),
            ],
            options={
                'verbose_name': 'Member',
                'db_table': 'db_member',
            },
        ),
    ]
