# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False, verbose_name=uuid.uuid4),
        ),
    ]
