# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20170616_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
