# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20170616_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone_number',
            field=models.CharField(max_length=16),
        ),
    ]
