# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20170616_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='last_name',
            field=models.CharField(max_length=128),
        ),
    ]
